### ISSUE TITLE
very nice initiative - getting an error

### ISSUE THREAD

**Issue by mihai-satmarean** [clayshek/ans-pve-win-templ#1]
Hi,
very nice initiative, and clever.
I am able to run it fine on a proxmox v6.2 with ZFS storage pool with image type changed to raw due to an error (unsupported format 'qcow2' at /usr/share/perl5/PVE/Storage/ZFSPoolPlugin.pm line 228), 
but when is about to boot installation I get this error into the windows installer
"**windows setup could not install one or more boot-critical drivers. To install Windows, make sure that the drivers are valid, and restart the installation.**"
Since I had not used windows in the last 5 years, I am a bit lost here.
Any hints?
Thanks!

**Comment by clayshek** [comment]
My hunch is that an additional virtio driver might be needed for raw, I only tested with qcow2, and from some super quick Googling, that format may not be supported on ZFS. Some more info here: https://pve.proxmox.com/wiki/Windows_10_guest_best_practices#Disk-Image_Format:_raw_vs_qcow2. That page also includes a link to download the latest virtio drivers that you can place inside /iso-files/drivers/virtio/
Also could be unrelated and have something to do with another required driver based on your setup. Believe Windows setup allows you to do some logging, but don't recall the specifics on that off hand. Let me know if you have any luck with that, or find any sort of solution that might be applicable in the code.

**Comment by mihai-satmarean** [comment]
Hi, thanks for the guidance.
Did not managed to move forward, the new virtio drivers acted the same,
I will try some more tricks in the coming days.

**Comment by clayshek** [comment]
@mihai-satmarean I was able to reproduce the issue, doesn't actually seem to have been related to raw vs qcow, and I'm not 100% certain what the cause was, but I updated existing virtio drivers in the repo, added new ones released since last year, and all is working correctly now. Hopefully with the new files here you'll see the same results.

**Comment by mihai-satmarean** [comment]
thanks a lot, that did worked!
