### ISSUE TITLE
ssh client and nfs client in autounatend.xml

### ISSUE THREAD

**Issue by mihai-satmarean** [clayshek/ans-pve-win-templ#3]
Hi,
many thanks for your efforts,
I had used this nice project to deploy a template on the proxmox.
It worked really nice.
The topic I have now is that we would need SSH and NFS enabled in the template.
I spend many hours trying to include that in the autounatend.xml unfortunately my windows skills did not got me to the end.
Would it be possible to add ssh and nfs services to be active?
Best regards,
Mihai

**Comment by clayshek** [comment]
Hi @mihai-satmarean, glad to hear this is working well for you. Generally I think the further needs you describe may be better suited for inclusion in a subsequent playbook to customize the Windows instance(s). The goal of this template playbook is be fairly generalized, but allow for later customization (hostname, networking, package installation, etc) before calling an instance complete. An example of how I'm doing further provisioning off of the template can be found here: https://github.com/clayshek/ans-pve-win-provision 

For the NFS enablement, take a look at the win_feature Ansible module, which should work for you whether you're talking about NFS server or client. For ssh, assume you would be looking to use Window's OpenSSH, and I _think_ win_feature would probably work for you as well, but more info on OpenSSH setup available here: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse 

Hope that helps.

**Comment by mihai-satmarean** [comment]
Hi @clayshek thanks for answering, I totally agree with you here, and I really like your provisioning model there.
The question I had is more at what point into the file, like [here maybe](https://github.com/clayshek/ans-pve-win-templ/blob/cbae1aa8710902bd01bfd0fa93941e99bebcac0a/autounattend.xml.tpl#L136) to include the powershell commands that activate the ssh based on windows documentation.
The reason for this is to have the ssh connectivity available for further ansible configuration avoiding bootstrapping through winrm or other means.
Nfs and other features, can be done afterwards with the method you suggested - win_feature.

So the question remains :) where would you put the powershell commands in the autounatend.xml so the ssh is active at reboot?
The scenario here is that in the template we place a batch file that runs a curl command against the ansible tower and reports the IP and other details so the new VM is finally configured in the first boot.
Hope this make s sense.

Best regards,
Mihai
