### ISSUE TITLE
quemu agent in windows

### ISSUE THREAD

**Issue by mihai-satmarean** [clayshek/ans-pve-win-templ#4]
Hi There,
another topic it comes to the scene we need to install the quemu agent.
Since we already put the virtio drivers can we do this too?
What would your recommendation be?
Best regards,
Mihai

**Comment by clayshek** [comment]
The qemu guest agent should be part of the template as of this PR being merged: https://github.com/clayshek/ans-pve-win-templ/pull/2

Note that I believe this just installs, but doesn't enable the agent unless 'agent: enabled' is set appropriately in the vars.yml file

Are you seeing otherwise?

**Comment by mihai-satmarean** [comment]
Will give it a try these days. 
Thanks!

**Comment by mihai-satmarean** [comment]
Hi, the last build of the template does indeed installs the quemu.
Thanks!
